### ISSUE TITLE
Feature Request: wait on user to enter in building / department information

### ISSUE THREAD

**Issue by aaplguru** [Jamf-Concepts/Setup-Manager#11]
For policies scoped to department or building this would come in handy. Maybe optional preference which enables wait on user info completion if this necessary for correct deploying these policies. If not necessary or set, SM can proceed while waiting on user input.

**Comment by scriptingosx** [comment]
This has been implemented with [v1.1beta](https://github.com/jamf/Setup-Manager-private/releases/tag/v1.1beta). Please test and let us know if this works for you.
