### ISSUE TITLE
Help window rendering issues

### ISSUE THREAD

**Issue by entusdictus** [Jamf-Concepts/Setup-Manager#12]
I have discovered multiple rendering issues with the help window. 

First issue: text is cut off when there is no help link added.
<img width="1160" alt="Text only" src="https://github.com/Jamf-Concepts/Setup-Manager/assets/14052665/1cfc3789-65af-4f1b-833a-6fe0960c06c4">

This is the text that should be displayed:
We are sorry that you are experiencing this inconvenience with your new Mac. Please contact the Corporate User Help Desk right away and we will take a look at your Mac.

Second issue: when the help link is too long, the QR code is larger than the help window and also renders above the help text.
![Text and Link](https://github.com/Jamf-Concepts/Setup-Manager/assets/14052665/1b990214-aa48-48ab-9b25-3c14fb2d5c7b)

Here one example link:
https://my-freaky-internal-website.net/community/company/it-en/it-systems-service-and-support/it-support-it-helpdesk-en/my-link-is-way-too-long-and-I-know-it

**Comment by jladders** [comment]
I have noticed a white box at the top of ours when we tried enrolling with Sequoia, similar to yours but our logo and text is still present.  It seems ok on Sonoma

**Comment by entusdictus** [comment]
In my case, the white box is only because I stripped off the company logos from the screenshot as I don't have the permission to use them publicly 😊

**Comment by scriptingosx** [comment]
> I have noticed a white box at the top of ours when we tried enrolling with Sequoia, similar to yours but our logo and text is still present. It seems ok on Sonoma

I am aware of the window title bar rendering with a different background in Sequoia. Will need to move my dev machine to Sequoia beta before I can fix that...

**Comment by scriptingosx** [comment]
This has been implemented with [v1.1beta](https://github.com/jamf/Setup-Manager-private/releases/tag/v1.1beta). Please test and let us know if this works for you.

**Comment by entusdictus** [comment]
Fixed for us, thank you!
