### ISSUE TITLE
Bug: User-initiated Enrollment issue with M3 chip

### ISSUE THREAD

**Issue by ecanault** [Jamf-Concepts/Setup-Manager#17]
Hi,

When manually enrolling a Mac with M3 chip, we deploy the Setup Manager package with a policy using the Enrollment Complete trigger.
We have checked that the configuration profile is deployed **before** the package, but unfortunately when Setup Manager is launched, there is no customized deployment: it opens generic texts and icons, performs the steps 1 to 6 preparation, then asked to Continue without deploying anything.

No probem with M3 chip and Automated Device Enrollment process when the Setup Manager package is deployed through a PreStage profile.
No problem also with M1 chip and either Automated Device Enrollment or User-initiated Enrollment.

Thanks,
Emmanuel Canault

**Comment by scriptingosx** [comment]
Which version of macOS?

How did you check "that the configuration profile is deployed **before** the package"?

**Comment by ecanault** [comment]
macOS 14.5 was used.

We check the configuration profile deployment by keeping System Settings opened on the Profiles pane (as it displays contents dynamically) and having also the Utilities folder opened to sees that the app appears after the configuration profile.

**Comment by scriptingosx** [comment]
Have you tested this with Setup Manager 1.1beta?

**Comment by ecanault** [comment]
@scriptingosx 

I took the time to test 1.1beta with :
- macOS 14.5
- macOS 15.0
- macOS 15.0.1
- macOS 15.1beta7

Setup Manager was working as expected each time now: I think you can close this one 😊

Thanks,
Emmanuel

**Comment by scriptingosx** [comment]
Awesome! Thank you! (BTW: you can close issues, as well)
