### ISSUE TITLE
Feature Request: Any chance this could be configured to run over the login window?

### ISSUE THREAD

**Issue by wakco** [Jamf-Concepts/Setup-Manager#18]
The idea being that instead of running it over the setup screens, and therefore requiring that all options to auto-advance or skip setup screen be disabled, would it be possible to have it start once the loginwindow appears, and therefore potentially blocking login until it's finished?

**Comment by wakco** [comment]
I ask because I'm trying to do that with swiftDialog (unsuccessfully so far, although I have managed to get swiftDialog to appear after a logout, just not after the setup screens, yet).

**Comment by scriptingosx** [comment]
This has been implemented with [v1.1beta](https://github.com/jamf/Setup-Manager-private/releases/tag/v1.1beta). Please test and let us know if this works for you.
