### ISSUE TITLE
"Wait" action type switches to "Watch Path' when saving custom schema

### ISSUE THREAD

**Issue by but-a-thought** [Jamf-Concepts/Setup-Manager#22]
When using the **"Wait"** action type, after saving, it switches to **"Watch Path"**.

**Comment by scriptingosx** [comment]
this comes from the fact that both actions contain a `wait` key. This chokes the parser when it re-opens the profile...

**Comment by scriptingosx** [comment]
quick solution was to remove the `wait` action. The new schema should be available in the Jamf Pro UI when you create a _new_ profile. Please test!
