### ISSUE TITLE
New JSON Schema adds invalid key to the plist

### ISSUE THREAD

**Issue by Uggbert** [Jamf-Concepts/Setup-Manager#23]
When using json schema switching to plist view shows that a new entry under <key>enrollmentActions</key> is created. highlighted below

```
<key>enrollmentActions</key>
 >>>> <key>actions</key> <<<<
      <array>
       <dict>
          <key>label</key>
          <string>LabelName</string>
          <key>icon</key>
          <string>IconPath.filename</string>
          <key>policy</key>
          <string>JamfPolicyTrigger</string>
        </dict>
        { ... }
</array>
 >>>> </dict> <<<<
```

This breaks the contents of enrollmentActions, so they never end up firing.

I think this can be fixed if its possible to move the 'Add Item' button directly under the Enrolment Actions and remove the single entry for 'Actions'

**Comment by duggan1972** [comment]
I'm seeing this issue as well

**Comment by scriptingosx** [comment]
An updated schema should be available when you create a new profile in the Jamf Pro UI. Please test!
