### ISSUE TITLE
Feature request:  JSON Schema

### ISSUE THREAD

**Issue by g0n5ch0r3k** [Jamf-Concepts/Setup-Manager#26]
Can we have a JSON Schema, or should i create one and upload it?

I´ve seen that there was one in the configuration profile jamf repository in a customer instance, but it´s gone and was missing a lot of keys.

Thanks

**Comment by Uggbert** [comment]
there already is one -  #21

**Comment by g0n5ch0r3k** [comment]
Okay, didn't see that. Anyway to get that raw json schema, to add the keys.

But it's also not completely: "Note: localized fields (title, message, label etc.) are not yet possible here. We are working on that. For now, keep handcrafting the property list xml for localized messages"

**Comment by scriptingosx** [comment]
We are working on completing the json schema, if you are missing anything (that isn’t documented yet) or find other errors, please create issues with specific descriptions
