### ISSUE TITLE
Policy scope and limitations 

### ISSUE THREAD

**Issue by neilv54** [Jamf-Concepts/Setup-Manager#32]
You define a trigger in the configuration profile, the trigger is scoped to a smart group or to a security group in the limitation and the computer is not part of that scoping.
The icon app will show as successful, even though nothing was delivered.
Is there a way to define scoping?

**Comment by scriptingosx** [comment]
No, scoping is defined in Jamf Pro and Setup Manager cannot influence this. All Setup Manager can report is that the command that triggered the custom policy ran successfully. There is no way to judge on-device whether the device should have been in scope or not.

There seems to be an issue with 11.9 (and possibly earlier versions) where a computer drops out of scope of smart groups while they are recalculating (i.e. right after a recon) which seems to affect some Setup Manager workflows. I have no way to determine whether this is affecting you, but I would recommend testing with 11.9.1?
