### ISSUE TITLE
If profile is only scoped in prestage it may be removed before Setup Manager runs due to PI112111

### ISSUE THREAD

**Issue by zpropheter** [Jamf-Concepts/Setup-Manager#34]
When scoping config profiles in prestage it's presumed they will remain on device until reaching the login screen/desktop.
If you scope only to the prestage for Setup Manager and try to run it will error out saying there's no profile assigned. This appears to be mainly affected when the prestage is affected by PI112111

**Comment by scriptingosx** [comment]
Yes, this is documented: https://github.com/Jamf-Concepts/Setup-Manager/blob/main/Docs/JamfPro-QuickStart.md#scoping-and-prestage

> Scope the configuration profile to the computers you want to run Setup Manager on

This is a behavior of Jamf Pro that Setup Manager cannot directly Andreas of fix
