### ISSUE TITLE
Feature Request - Pause JAMF Framework

### ISSUE THREAD

**Issue by Uggbert** [Jamf-Concepts/Setup-Manager#37]
During long deployments (such as lab devices) where lots of software deployments and configuration is taking place I have a script that pauses the jamf framework - killing jamf binary and unloads the schedule task

```
jamftasks=($( find /Library/LaunchDaemons -iname "*task*" -type f -maxdepth 1 ))
jamfpid=$( ps -ax | grep "jamf policy -randomDelaySeconds" | grep -v "grep" | awk '{ print $1 }' )
for ((i=0;i<${#jamftasks[@]};i++)); do
	launchctl unload -w "${jamftasks[$i]}"
done

if [ "$jamfpid" != "" ]; then
	kill -9 "$jamfpid"
fi

exit 0
```

This ensures all manual triggers are executed in order without interruption, then at the end of deployment this then reloads as normal to allow normal recon and any other 'check-in' policies to run.

Is it possible to add something like this as a bool value to the config? if not, no worries I can keep this bookending my deployments.

**Comment by scriptingosx** [comment]
Setup Manager already waits for the jamf processes to be finished and then unloads the background daemon while it is running its workflow (this is one of the steps in the "Getting Ready" phase). Then it reloads the background daemon when it is done.

If you are still seeing problems:

1) please test with Setup Manager 1.1beta
2) if the problems persist with 1.1beta, please share `/Library/Logs/Setup Manager.log` and `/var/log/jamf.log`

**Comment by Uggbert** [comment]
Ok then this was not working for me with the 1.1 beta. It's what prompted
me to write this, I'll take a look at the logs!
Kind Regards,

Graeme Urquhart
