### ISSUE TITLE
default key in assetTag user entry not populating

### ISSUE THREAD

**Issue by fraserhess** [Jamf-Concepts/Setup-Manager#43]
I am trying to prepopulate a default value for `assetTag` during user entry in the 1.1beta. The value is not populating. Otherwise, the prompt is working fine: it has a placeholder value and the regex validates entries correctly.

Relevant portion of configuration:
```
<key>userEntry</key>
<dict>
	<key>assetTag</key>
	<dict>
		<key>default</key>
		<string>99998</string>
		<key>placeholder</key>
		<string>12345</string>
		<key>validation</key>
		<string>[1-9]\d{4}</string>
		<key>validationMessage</key>
		<string>A barcode number between 10000 and 99999</string>
	</dict>
</dict>
```

**Comment by scriptingosx** [comment]
fixed in 1.1
