### ISSUE TITLE
Installomator Policy via Setup Manager broken

### ISSUE THREAD

**Issue by heinenjh** [Jamf-Concepts/Setup-Manager#45]
We have policies for various app installations via Installomator in Jamf Pro.
Setup Manager triggers these policies to install the apps.
At the moment we dont use the intallomator included in setup manager
[M365-Failed-SetupManager.txt](https://github.com/user-attachments/files/17379669/M365-Failed-SetupManager.txt)
[M365-Success-SelfService.txt](https://github.com/user-attachments/files/17379671/M365-Success-SelfService.txt)

So far this has always worked well. We suddenly noticed that during the installation with Setup Manager apps such as M365, Citrix Workspace, Edge are no longer installed.
There is a timeout in the policy log on the Mac in Jamf Pro.
If I start the same policy via Self Service, the package installs correctly.
Logs of both cases attached.

**Comment by scriptingosx** [comment]
Are you running Setup Manager from the Prestage (at Automated Device Enrollment) or at a different time (User initiated enrollment)?

The Teams log shows that your Installomator script used in the policy is out of date. update to 10.6 first https://github.com/Installomator/Installomator/releases

It also shows that Installomator believes that Teams is already installed and is attempting to update it using the `msupdate` CLI tool (MS AutoUpdate). If using the latest version of Installomator doesn't fix the issues, try adding an `INSTALL=force` argument, which will tell Installomator to download and install in all cases, and not attempt an update.

**Comment by heinenjh** [comment]
Updating the script to version 10.6 did not help. with the argument `INSTALL=force` it works now. Thanks for your support!
