### ISSUE TITLE
Feature Request - Add the ablity to choose a Site during Setup.

### ISSUE THREAD

**Issue by maburdett** [Jamf-Concepts/Setup-Manager#47]
Currently in custom DEPNotify scripting use Sites to customize the naming of the device, set what packages are installed, and change the branding and Service desk contacts that support the device at that site.

It would be a great feature for us if setup manager could request and set the Site, and then use a configuration profile designed for that site deployment of the devices.

For example, each site, we use a 3 destination for the site chosen + the asset tag number we collected to set the computer name, hostname, Bonjour name, and NetBIOS name to  "Site-AssetTag"

Each site has its own unique software that is installed.
Each site has its own service desk and contacts we need to convey to the user.     There is not much that can done here unless JAMF gives us SelfServce branding for each site and prestage Enrollment Customization Configuration for each site.

**Comment by scriptingosx** [comment]
Duplicate #19

**Comment by scriptingosx** [comment]
Also, maybe this feature of 1.1beta fits? https://github.com/Jamf-Concepts/Setup-Manager/blob/main/Docs/JamfPro-TwoPhase.md

**Comment by MLBZ521** [comment]
@maburdett Each Site can have it's own, specific, custom Enrollment Customization.  These are not Top-Level only items.
