### ISSUE TITLE
“runAt” description is a bit unclear

### ISSUE THREAD

**Issue by erefneb** [Jamf-Concepts/Setup-Manager#48]
https://github.com/Jamf-Concepts/Setup-Manager/blob/main/ConfigurationProfile.md#runat
The last sentence of the “runAt” description is a bit unclear. 
It currently reads, “A setting of loginwindow will only with enrollment…”
I think it should begin, “A setting of loginwindow will only work with enrollment…”

**Comment by scriptingosx** [comment]
fixed in 1.1
